
// ---------------------------------------------------------------------------------------------------------
// chipmunk_types.h
//----------------------------------------------------------------------------------------------------------
typedef cpFloat double;
typedef cpBool uchar;
typedef cpDataPointer VoidPtr;
typedef cpGroup int64;
typedef cpBitmask uint;

interface cpVect
{
	void cpVect();
	attribute cpFloat x;
    attribute cpFloat y;
};

interface cpTransform {
	void cpTransform();
	attribute cpFloat a;
	attribute cpFloat b;
	attribute cpFloat c;
	attribute cpFloat d;
	attribute cpFloat tx; 
	attribute cpFloat ty;
};

interface cpMat2x2 {
	void cpMat2x2();
	attribute cpFloat a; 
	attribute cpFloat b;
	attribute cpFloat c;
	attribute cpFloat d;
};


// ---------------------------------------------------------------------------------------------------------
// cpBB.h
//----------------------------------------------------------------------------------------------------------
interface cpBB
{
    void cpBB();
    attribute cpFloat l;
    attribute cpFloat b;
    attribute cpFloat r;
    attribute cpFloat t;
	
	[Static,Value] cpBB cpBBNew([Const] cpFloat l, [Const] cpFloat b, [Const] cpFloat r, [Const] cpFloat t);
	[Static,Value] cpBB cpBBNewForExtents([Const,Deref] cpVect c, [Const] cpFloat hw, [Const] cpFloat hh);
	[Static,Value] cpBB cpBBNewForCircle([Const,Deref] cpVect p, [Const] cpFloat r);
	[Static] cpBool cpBBIntersects([Const,Deref] cpBB a, [Const,Deref] cpBB b);
	[Static] cpBool cpBBContainsBB([Const,Deref] cpBB bb, [Const,Deref] cpBB other);
	[Static] cpBool cpBBContainsVect([Const,Deref] cpBB bb, [Const,Deref] cpVect v);
	[Static,Value] cpBB cpBBMerge([Const,Deref] cpBB a, [Const,Deref] cpBB b);
	[Static,Value] cpBB cpBBExpand([Const,Deref] cpBB bb, [Const,Deref] cpVect v);
	[Static,Value] cpVect cpBBCenter([Deref] cpBB bb);
	[Static] cpFloat cpBBArea([Deref] cpBB bb);
	[Static] cpFloat cpBBMergedArea([Deref] cpBB a, [Deref] cpBB b);
	[Static] cpFloat cpBBSegmentQuery([Deref] cpBB bb, [Deref] cpVect a, [Deref] cpVect b);
	[Static] cpBool cpBBIntersectsSegment([Deref] cpBB bb, [Deref] cpVect a, [Deref] cpVect b);
	[Static,Value] cpVect cpBBClampVect([Const,Deref] cpBB bb, [Const,Deref] cpVect v);
	[Static,Value] cpVect cpBBWrapVect([Const,Deref] cpBB bb, [Const,Deref] cpVect v);
	[Static,Value] cpBB cpBBOffset([Const,Deref] cpBB bb, [Const,Deref] cpVect v);
};


// ---------------------------------------------------------------------------------------------------------
// cpBody.h
//----------------------------------------------------------------------------------------------------------
// enum cpBodyTypeHL {
// 	"CP_BODY_TYPE_DYNAMIC",
// 	"CP_BODY_TYPE_KINEMATIC",
// 	"CP_BODY_TYPE_STATIC"
// };

[Internal="cpBody"]	
interface cpBody {
	
	void cpBody();

	[Static] cpBody cpBodyAlloc();

	[Static] cpBody cpBodyInit(cpBody body, cpFloat mass, cpFloat moment);

	[Static] cpBody cpBodyNew(cpFloat mass, cpFloat moment);

	[Static] cpBody cpBodyNewKinematic();

	[Static] cpBody cpBodyNewStatic();

	[CObject] void cpBodyDestroy();
	
	[CObject] void cpBodyFree();

	[CObject] void cpBodyActivate();

	//[CObject] void cpBodyActivateStatic( cpShape filter);

	[CObject] void cpBodySleep();

	[CObject] void cpBodySleepWithGroup(cpBody group);

	[CObject] cpBool cpBodyIsSleeping();

	//[CObject] cpBodyType cpBodyGetType();

	//[CObject] void cpBodySetType(cpBodyType type);

	// [CObject] cpSpace cpBodyGetSpace();

	[CObject] cpFloat cpBodyGetMass();

	[CObject] void cpBodySetMass(cpFloat m);

	[CObject] cpFloat cpBodyGetMoment();

	[CObject] void cpBodySetMoment(cpFloat i);

	[CObject,Value] cpVect cpBodyGetPosition();

	[CObject] void cpBodySetPosition([Deref] cpVect pos);

	[CObject,Value] cpVect cpBodyGetCenterOfGravity();
	
	[CObject] void cpBodySetCenterOfGravity([Deref] cpVect cog);

	[CObject,Value] cpVect cpBodyGetVelocity();

	[CObject] void cpBodySetVelocity([Deref] cpVect velocity);

	[CObject,Value] cpVect cpBodyGetForce();

	[CObject] void cpBodySetForce([Deref] cpVect force);

	[CObject] cpFloat cpBodyGetAngle();

	[CObject] void cpBodySetAngle(cpFloat a);

	[CObject] cpFloat cpBodyGetAngularVelocity();

	[CObject] void cpBodySetAngularVelocity(cpFloat angularVelocity);

	[CObject] cpFloat cpBodyGetTorque();

	[CObject] void cpBodySetTorque(cpFloat torque);

	[CObject,Value] cpVect cpBodyGetRotation();

	//[CObject] cpDataPointer cpBodyGetUserData();

	//[CObject] void cpBodySetUserData(cpDataPointer userData);

	// [CObject] void cpBodySetVelocityUpdateFunc(cpBodyVelocityFunc velocityFunc); // TODO

	// [CObject] void cpBodySetPositionUpdateFunc(cpBodyPositionFunc positionFunc); // TODO

	[CObject] void cpBodyUpdateVelocity([Deref] cpVect gravity, cpFloat damping, cpFloat dt);
	
	[CObject] void cpBodyUpdatePosition(cpFloat dt);

	[CObject,Value] cpVect cpBodyLocalToWorld([Const,Deref] cpVect point);

	[CObject,Value] cpVect cpBodyWorldToLocal([Const,Deref] cpVect point);

	[CObject] void cpBodyApplyForceAtWorldPoint([Deref] cpVect force, [Deref] cpVect point);

	[CObject] void cpBodyApplyForceAtLocalPoint([Deref] cpVect force, [Deref] cpVect point);

	[CObject] void cpBodyApplyImpulseAtWorldPoint([Deref] cpVect impulse, [Deref] cpVect point);
	
	[CObject] void cpBodyApplyImpulseAtLocalPoint([Deref] cpVect impulse, [Deref] cpVect point);

	[CObject,Value] cpVect cpBodyGetVelocityAtWorldPoint([Deref] cpVect point);
	
	[CObject,Value]  cpVect cpBodyGetVelocityAtLocalPoint([Deref] cpVect point);

	[CObject] cpFloat cpBodyKineticEnergy();

	// TODO
	// [CObject] void cpBodyEachShape(cpBodyShapeIteratorFunc func, void *data);

	// [CObject] void cpBodyEachConstraint(cpBodyConstraintIteratorFunc func, void *data);

	// [CObject] void cpBodyEachArbiter(cpBodyArbiterIteratorFunc func, void *data);
};


// ---------------------------------------------------------------------------------------------------------
// cpShape.h
//----------------------------------------------------------------------------------------------------------

interface cpPointQueryInfo 
{
	void cpPointQueryInfo();
	[Const] attribute cpShape shape;
	[Value] attribute cpVect point;
	attribute cpFloat distance;
	[Value] attribute cpVect gradient;
};

interface cpSegmentQueryInfo {
	void cpSegmentQueryInfo();
	[Const] attribute cpShape shape;
	[Value] attribute cpVect point;
	[Value] attribute cpVect normal;
	attribute cpFloat alpha;
};

interface cpShapeFilter {
	attribute cpGroup group;
	attribute cpBitmask categories;
	attribute cpBitmask mask;
};

interface cpShape
{
	void cpShape();

	[Static,Value] cpShapeFilter cpShapeFilterNew(cpGroup group, cpBitmask categories, cpBitmask mask);

	[CObject] void cpShapeDestroy();

	[CObject] void cpShapeFree();

	[CObject,Value] cpBB cpShapeCacheBB();

	[CObject,Value] cpBB cpShapeUpdate([Deref] cpTransform transform);

	[CObject] cpFloat cpShapePointQuery([Deref] cpVect p, cpPointQueryInfo out);

	[CObject] cpBool cpShapeSegmentQuery([Deref] cpVect a, [Deref] cpVect b, cpFloat radius, cpSegmentQueryInfo info);

	[Static,Value] cpContactPointSet cpShapesCollide([Const] cpShape a, [Const] cpShape b);

	[CObject] cpSpace cpShapeGetSpace();

	[CObject] cpBody cpShapeGetBody();

	[CObject] void cpShapeSetBody(cpBody body);

	[CObject] cpFloat cpShapeGetMass();

	[CObject] void cpShapeSetMass(cpFloat mass);

	[CObject] cpFloat cpShapeGetDensity();

	[CObject] void cpShapeSetDensity(cpFloat density);

	[CObject] cpFloat cpShapeGetMoment();

	[CObject] cpFloat cpShapeGetArea();

	[CObject,Value] cpVect cpShapeGetCenterOfGravity();

	[CObject,Value] cpBB cpShapeGetBB();

	[CObject] cpBool cpShapeGetSensor();

	[CObject] void cpShapeSetSensor(cpBool sensor);

	[CObject] cpFloat cpShapeGetElasticity();

	[CObject] void cpShapeSetElasticity(cpFloat elasticity);

	[CObject] cpFloat cpShapeGetFriction();

	[CObject] void cpShapeSetFriction(cpFloat friction);

	[CObject,Value] cpVect cpShapeGetSurfaceVelocity();

	[CObject] void cpShapeSetSurfaceVelocity([Deref] cpVect surfaceVelocity);

	[CObject] cpDataPointer cpShapeGetUserData();

	[CObject] void cpShapeSetUserData(cpDataPointer userData);

	// [CObject] cpCollisionType cpShapeGetCollisionType();

	// [CObject] void cpShapeSetCollisionType(cpCollisionType collisionType);

	[CObject,Value] cpShapeFilter cpShapeGetFilter();

	[CObject] void cpShapeSetFilter([Deref] cpShapeFilter filter);
};

interface cpCircleShape
{
	[Static] cpCircleShape cpCircleShapeAlloc();
	[Static] cpCircleShape cpCircleShapeInit(cpCircleShape circle, cpBody body, cpFloat radius, [Deref] cpVect offset);
	[Static] cpShape cpCircleShapeNew(cpBody body, cpFloat radius, [Deref] cpVect offset);
	[Static,Value] cpVect cpCircleShapeGetOffset([Const] cpShape shape);
	[Static] cpFloat cpCircleShapeGetRadius([Const] cpShape shape);
};

interface cpSegmentShape
{
	[Static] cpSegmentShape cpSegmentShapeAlloc();

	[Static] cpSegmentShape cpSegmentShapeInit(cpSegmentShape seg, cpBody body, 
				[Deref] cpVect a, [Deref] cpVect b, cpFloat radius);

	[Static] cpShape cpSegmentShapeNew(cpBody body, [Deref] cpVect a, [Deref] cpVect b, cpFloat radius);

	[Static] void cpSegmentShapeSetNeighbors(cpShape shape, [Deref] cpVect prev, [Deref] cpVect next);

	[Static,Value] cpVect cpSegmentShapeGetA([Const] cpShape shape);

	[Static,Value] cpVect cpSegmentShapeGetB([Const] cpShape shape);

	[Static,Value] cpVect cpSegmentShapeGetNormal([Const] cpShape shape);

	[Static] cpFloat cpSegmentShapeGetRadius([Const] cpShape shape);
};

// ---------------------------------------------------------------------------------------------------------
// cpSpace.h
//----------------------------------------------------------------------------------------------------------
interface cpSpace
{
	[Static] cpSpace cpSpaceInit(cpSpace space);

	[Static] cpSpace cpSpaceNew();

	[CObject] void cpSpaceDestroy();

	[CObject] void cpSpaceFree();

	[CObject] int cpSpaceGetIterations();

	[CObject] void cpSpaceSetIterations(int iterations);

	[CObject,Value] cpVect cpSpaceGetGravity();

	[CObject] void cpSpaceSetGravity([Deref] cpVect gravity);

	[CObject] cpFloat cpSpaceGetDamping();

	[CObject] void cpSpaceSetDamping(cpFloat damping);

	[CObject] cpFloat cpSpaceGetIdleSpeedThreshold();

	[CObject] void cpSpaceSetIdleSpeedThreshold(cpFloat idleSpeedThreshold);

	[CObject] cpFloat cpSpaceGetSleepTimeThreshold();

	[CObject] void cpSpaceSetSleepTimeThreshold(cpFloat sleepTimeThreshold);

	[CObject] cpFloat cpSpaceGetCollisionSlop();

	[CObject] void cpSpaceSetCollisionSlop(cpFloat collisionSlop);

	[CObject] cpFloat cpSpaceGetCollisionBias();

	[CObject] void cpSpaceSetCollisionBias(cpFloat collisionBias);

	// [CObject] cpTimestamp cpSpaceGetCollisionPersistence();

	// [CObject] void cpSpaceSetCollisionPersistence(cpTimestamp collisionPersistence);

	[CObject] cpDataPointer cpSpaceGetUserData();

	[CObject] void cpSpaceSetUserData(cpDataPointer userData);

	[CObject] cpBody cpSpaceGetStaticBody();

	[CObject] cpFloat cpSpaceGetCurrentTimeStep();

	[CObject] cpBool cpSpaceIsLocked();

	// [CObject] cpCollisionHandler *cpSpaceAddDefaultCollisionHandler();

	// [CObject] cpCollisionHandler *cpSpaceAddCollisionHandler(cpCollisionType a, cpCollisionType b);

	// [CObject] cpCollisionHandler *cpSpaceAddWildcardHandler(cpCollisionType type);

	[CObject] void cpSpaceAddShapeVoid(cpShape shape); // README. I had to replace the original functions because each call was duplicating the space.

	[CObject] void cpSpaceAddBodyVoid(cpBody body); // README. I had to replace the original functions because each call was duplicating the space.

	[CObject] cpConstraint cpSpaceAddConstraint(cpConstraint constraint);

	[CObject] void cpSpaceRemoveShape(cpShape shape);

	[CObject] void cpSpaceRemoveBody(cpBody body);

	[CObject] void cpSpaceRemoveConstraint(cpConstraint constraint);

	[CObject] cpBool cpSpaceContainsShape(cpShape shape);

	[CObject] cpBool cpSpaceContainsBody(cpBody body);

	[CObject] cpBool cpSpaceContainsConstraint(cpConstraint constraint);

	// [CObject] cpBool cpSpaceAddPostStepCallback(cpPostStepFunc func, void *key, void *data);

	// [CObject] void cpSpacePointQuery(cpVect point, cpFloat maxDistance, cpShapeFilter filter, cpSpacePointQueryFunc func, void *data);

	// [CObject] cpShape cpSpacePointQueryNearest(cpVect point, cpFloat maxDistance, cpShapeFilter filter, cpPointQueryInfo *out);

	// [CObject] void cpSpaceSegmentQuery(cpVect start, cpVect end, cpFloat radius, cpShapeFilter filter, cpSpaceSegmentQueryFunc func, void *data);

	// [CObject] cpShape cpSpaceSegmentQueryFirst(cpVect start, cpVect end, cpFloat radius, cpShapeFilter filter, cpSegmentQueryInfo *out);

	// [CObject] void cpSpaceBBQuery(cpBB bb, cpShapeFilter filter, cpSpaceBBQueryFunc func, void *data);

	// [CObject] cpBool cpSpaceShapeQuery(cpShape shape, cpSpaceShapeQueryFunc func, void *data);

	// [CObject] void cpSpaceEachBody(cpSpaceBodyIteratorFunc func, void *data);

	// [CObject] void cpSpaceEachShape(cpSpaceShapeIteratorFunc func, void *data);

	// [CObject] void cpSpaceEachConstraint(cpSpaceConstraintIteratorFunc func, void *data);

	[CObject] void cpSpaceReindexStatic();

	[CObject] void cpSpaceReindexShape(cpShape shape);

	[CObject] void cpSpaceReindexShapesForBody(cpBody body);

	[CObject] void cpSpaceUseSpatialHash(cpFloat dim, int count);

	[CObject] void cpSpaceStep(cpFloat dt);
};


// ---------------------------------------------------------------------------------------------------------
// cpArbiter.h
//----------------------------------------------------------------------------------------------------------
interface cpContactPointSet {
	
};

interface cpArbiter
{
	[CObject] cpFloat cpArbiterGetRestitution();

	[CObject] void cpArbiterSetRestitution(cpFloat restitution);

	[CObject] cpFloat cpArbiterGetFriction();

	[CObject] void cpArbiterSetFriction(cpFloat friction);

	[CObject,Value] cpVect cpArbiterGetSurfaceVelocity();

	[CObject] void cpArbiterSetSurfaceVelocity([Deref] cpVect vr);

	[CObject] cpDataPointer cpArbiterGetUserData();

	[CObject] void cpArbiterSetUserData(cpDataPointer userData);

	[CObject,Value] cpVect cpArbiterTotalImpulse();

	[CObject] cpFloat cpArbiterTotalKE();

	[CObject] cpBool cpArbiterIgnore();

	// CP_EXPORT void cpArbiterGetShapes(const cpArbiter *arb, cpShape **a, cpShape **b);

	// CP_EXPORT void cpArbiterGetBodies(const cpArbiter *arb, cpBody **a, cpBody **b);

	[CObject,Value] cpContactPointSet cpArbiterGetContactPointSet();

	[CObject] void cpArbiterSetContactPointSet(cpContactPointSet set);

	[CObject] cpBool cpArbiterIsFirstContact();

	[CObject] cpBool cpArbiterIsRemoval();

	[CObject] int cpArbiterGetCount();

	[CObject,Value] cpVect cpArbiterGetNormal();

	[CObject,Value] cpVect cpArbiterGetPointA(int i);

	[CObject,Value] cpVect cpArbiterGetPointB(int i);

	[CObject] cpFloat cpArbiterGetDepth(int i);

	[CObject] cpBool cpArbiterCallWildcardBeginA(cpSpace space);

	[CObject] cpBool cpArbiterCallWildcardBeginB(cpSpace space);

	[CObject] cpBool cpArbiterCallWildcardPreSolveA(cpSpace space);

	[CObject] cpBool cpArbiterCallWildcardPreSolveB(cpSpace space);

	[CObject] void cpArbiterCallWildcardPostSolveA(cpSpace space);

	[CObject] void cpArbiterCallWildcardPostSolveB(cpSpace space);

	[CObject] void cpArbiterCallWildcardSeparateA(cpSpace space);

	[CObject] void cpArbiterCallWildcardSeparateB(cpSpace space);
};


// ---------------------------------------------------------------------------------------------------------
// cpConstraint.h
//----------------------------------------------------------------------------------------------------------
interface cpConstraint
{
	[CObject] void cpConstraintDestroy();

	[CObject] void cpConstraintFree();

	[CObject] cpSpace cpConstraintGetSpace();

	[CObject] cpBody cpConstraintGetBodyA();

	[CObject] cpBody cpConstraintGetBodyB();

	[CObject] cpFloat cpConstraintGetMaxForce();
	
	[CObject] void cpConstraintSetMaxForce(cpFloat maxForce);

	[CObject] cpFloat cpConstraintGetErrorBias();

	[CObject] void cpConstraintSetErrorBias(cpFloat errorBias);

	[CObject] cpFloat cpConstraintGetMaxBias();

	[CObject] void cpConstraintSetMaxBias(cpFloat maxBias);

	[CObject] cpBool cpConstraintGetCollideBodies();

	[CObject] void cpConstraintSetCollideBodies(cpBool collideBodies);

	//[CObject] cpConstraintPreSolveFunc cpConstraintGetPreSolveFunc();

	//[CObject] void cpConstraintSetPreSolveFunc(cpConstraintPreSolveFunc preSolveFunc);

	//[CObject] cpConstraintPostSolveFunc cpConstraintGetPostSolveFunc();

	//[CObject] void cpConstraintSetPostSolveFunc(cpConstraintPostSolveFunc postSolveFunc);

	[CObject] cpDataPointer cpConstraintGetUserData();

	[CObject] void cpConstraintSetUserData(cpDataPointer userData);

	[CObject] cpFloat cpConstraintGetImpulse();
};


// ---------------------------------------------------------------------------------------------------------
// cpDampedRotarySpring.h
//----------------------------------------------------------------------------------------------------------
interface cpDampedRotarySpring
{
	[Static] cpBool cpConstraintIsDampedRotarySpring([Const] cpConstraint constraint);

	[Static] cpDampedRotarySpring cpDampedRotarySpringAlloc();

	[Static] cpDampedRotarySpring cpDampedRotarySpringInit(cpDampedRotarySpring joint, 
			cpBody a, cpBody b, cpFloat restAngle, cpFloat stiffness, cpFloat damping);

	[Static] cpConstraint cpDampedRotarySpringNew(cpBody a, cpBody b, cpFloat restAngle, 
			cpFloat stiffness, cpFloat damping);

	[Static] cpFloat cpDampedRotarySpringGetRestAngle([Const] cpConstraint constraint);

	[Static] void cpDampedRotarySpringSetRestAngle(cpConstraint constraint, cpFloat restAngle);

	[Static] cpFloat cpDampedRotarySpringGetStiffness([Const] cpConstraint constraint);

	[Static] void cpDampedRotarySpringSetStiffness([Const] cpConstraint constraint, cpFloat stiffness);

	[Static] cpFloat cpDampedRotarySpringGetDamping([Const] cpConstraint constraint);

	[Static] void cpDampedRotarySpringSetDamping(cpConstraint constraint, cpFloat damping);

	// [Static] cpDampedRotarySpringTorqueFunc cpDampedRotarySpringGetSpringTorqueFunc(const cpConstraint *constraint);

	//[Static] void cpDampedRotarySpringSetSpringTorqueFunc(cpConstraint *constraint, cpDampedRotarySpringTorqueFunc springTorqueFunc);
};


// ---------------------------------------------------------------------------------------------------------
// cpDampedSpring.h
//----------------------------------------------------------------------------------------------------------
interface cpDampedSpring
{
	[Static] cpBool cpConstraintIsDampedSpring([Const] cpConstraint constraint);

	[Static] cpDampedSpring cpDampedSpringAlloc();

	[Static] cpDampedSpring cpDampedSpringInit(cpDampedSpring joint, cpBody a, cpBody b, 
			[Deref] cpVect anchorA, [Deref] cpVect anchorB, cpFloat restLength, cpFloat stiffness, cpFloat damping);

	[Static] cpConstraint cpDampedSpringNew(cpBody a, cpBody b, [Deref] cpVect anchorA, [Deref] cpVect anchorB, 
			cpFloat restLength, cpFloat stiffness, cpFloat damping);

	[Static,Value] cpVect cpDampedSpringGetAnchorA([Const] cpConstraint constraint);

	[Static] void cpDampedSpringSetAnchorA(cpConstraint constraint, [Deref] cpVect anchorA);

	[Static,Value] cpVect cpDampedSpringGetAnchorB([Const] cpConstraint constraint);

	[Static] void cpDampedSpringSetAnchorB(cpConstraint constraint, [Deref] cpVect anchorB);

	[Static] cpFloat cpDampedSpringGetRestLength([Const] cpConstraint constraint);

	[Static] void cpDampedSpringSetRestLength(cpConstraint constraint, cpFloat restLength);

	[Static] cpFloat cpDampedSpringGetStiffness([Const] cpConstraint constraint);

	[Static] void cpDampedSpringSetStiffness(cpConstraint constraint, cpFloat stiffness);

	[Static] cpFloat cpDampedSpringGetDamping([Const] cpConstraint constraint);

	[Static] void cpDampedSpringSetDamping(cpConstraint constraint, cpFloat damping);

	// [Static] cpDampedSpringForceFunc cpDampedSpringGetSpringForceFunc(const cpConstraint *constraint);

	// [Static] void cpDampedSpringSetSpringForceFunc(cpConstraint *constraint, cpDampedSpringForceFunc springForceFunc);
};


// ---------------------------------------------------------------------------------------------------------
// cpGearJoint.h
//----------------------------------------------------------------------------------------------------------
interface cpGearJoint
{
	[Static] cpBool cpConstraintIsGearJoint([Const]  cpConstraint constraint);

	[Static] cpGearJoint cpGearJointAlloc();

	[Static] cpGearJoint cpGearJointInit(cpGearJoint joint, cpBody a, cpBody b, cpFloat phase, cpFloat ratio);

	[Static] cpConstraint cpGearJointNew(cpBody a, cpBody b, cpFloat phase, cpFloat ratio);

	[Static] cpFloat cpGearJointGetPhase([Const] cpConstraint constraint);

	[Static] void cpGearJointSetPhase(cpConstraint constraint, cpFloat phase);

	[Static] cpFloat cpGearJointGetRatio([Const] cpConstraint constraint);

	[Static] void cpGearJointSetRatio(cpConstraint constraint, cpFloat ratio);
};


// ---------------------------------------------------------------------------------------------------------
// cpSimpleMotor.h
//----------------------------------------------------------------------------------------------------------
interface cpSimpleMotor
{
	[Static] cpBool cpConstraintIsSimpleMotor([Const] cpConstraint constraint);

	[Static] cpSimpleMotor cpSimpleMotorAlloc();

	[Static] cpSimpleMotor cpSimpleMotorInit(cpSimpleMotor joint, cpBody a, cpBody b, cpFloat rate);

	[Static] cpConstraint cpSimpleMotorNew(cpBody a, cpBody b, cpFloat rate);

	[Static] cpFloat cpSimpleMotorGetRate([Const] cpConstraint constraint);

	[Static] void cpSimpleMotorSetRate(cpConstraint constraint, cpFloat rate);
};


// ---------------------------------------------------------------------------------------------------------
// cpGrooveJoint.h
//----------------------------------------------------------------------------------------------------------
interface cpGrooveJoint
{
	[Static] cpBool cpConstraintIsGrooveJoint([Const] cpConstraint constraint);

	[Static] cpGrooveJoint cpGrooveJointAlloc();

	[Static] cpGrooveJoint cpGrooveJointInit(cpGrooveJoint joint, cpBody a, cpBody b, [Deref] cpVect groove_a, 
			[Deref] cpVect groove_b, [Deref] cpVect anchorB);

	[Static] cpConstraint cpGrooveJointNew(cpBody a, cpBody b, [Deref] cpVect groove_a, [Deref] cpVect groove_b, 
			[Deref] cpVect anchorB);

	[Static,Value] cpVect cpGrooveJointGetGrooveA([Const] cpConstraint constraint);

	[Static] void cpGrooveJointSetGrooveA(cpConstraint constraint, [Deref] cpVect grooveA);

	[Static,Value] cpVect cpGrooveJointGetGrooveB([Const] cpConstraint constraint);

	[Static] void cpGrooveJointSetGrooveB(cpConstraint constraint, [Deref] cpVect grooveB);

	[Static,Value] cpVect cpGrooveJointGetAnchorB([Const] cpConstraint constraint);

	[Static] void cpGrooveJointSetAnchorB(cpConstraint constraint, [Deref] cpVect anchorB);
};


// ---------------------------------------------------------------------------------------------------------
// chipmunk.h
//----------------------------------------------------------------------------------------------------------
interface Chipmunk2D 
{
	[Static] cpFloat cpMomentForCircle(cpFloat m, cpFloat r1, cpFloat r2, [Deref] cpVect offset);

	[Static] cpFloat cpAreaForCircle(cpFloat r1, cpFloat r2);
	
	[Static] cpFloat cpMomentForSegment(cpFloat m, [Deref,Cast="cpVect*"] cpVect a, [Deref] cpVect b, cpFloat radius);
	
	[Static] cpFloat cpMomentForPoly( cpFloat m, int count, [Const,Cast="cpVect*"] double[] verts, 
							[Deref] cpVect offset, cpFloat radius);

	[Static] cpFloat cpAreaForSegment([Deref] cpVect a, [Deref] cpVect b, cpFloat radius);

	[Static] cpFloat cpAreaForPoly([Const] int count, [Const,Cast="cpVect*"] double[] verts, cpFloat radius);

	[Static,Value] cpVect cpCentroidForPoly([Const] int count, [Cast="cpVect*"] double[] verts);

	[Static] cpFloat cpMomentForBox(cpFloat m, cpFloat width, cpFloat height);

	[Static] cpFloat cpMomentForBox2(cpFloat m, [Deref] cpBB box);

	[Static] int cpConvexHull(int count,  [Const,Cast="cpVect*"] double[] verts, 
							[Cast="cpVect*"] double[] result, int[] first, cpFloat tol);

	[Static,Value] cpVect cpClosetPointOnSegment( [Deref] cpVect p, 
							 [Deref] cpVect a, [Deref] cpVect b);

};
